// <auto-generated />
using System;
using LibraryProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryProject.Data.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260623143300_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LibraryProject.Data.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = 1850,
                            FirstName = "Иван",
                            LastName = "Вазов",
                            Nationality = "Българска"
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = 1863,
                            FirstName = "Алеко",
                            LastName = "Константинов",
                            Nationality = "Българска"
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = 1965,
                            FirstName = "Джоан",
                            LastName = "Роулинг",
                            Nationality = "Британска"
                        },
                        new
                        {
                            Id = 4,
                            BirthYear = 1892,
                            FirstName = "Джон Роналд Руел",
                            LastName = "Толкин",
                            Nationality = "Британска"
                        },
                        new
                        {
                            Id = 5,
                            BirthYear = 1903,
                            FirstName = "Джордж",
                            LastName = "Оруел",
                            Nationality = "Британска"
                        });
                });

            modelBuilder.Entity("LibraryProject.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            AvailableCopies = 5,
                            CategoryId = 1,
                            ISBN = "978-954-01-0001-1",
                            PublishYear = 1894,
                            Title = "Под игото"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            AvailableCopies = 3,
                            CategoryId = 1,
                            ISBN = "978-954-01-0002-2",
                            PublishYear = 1895,
                            Title = "Бай Ганьо"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            AvailableCopies = 8,
                            CategoryId = 2,
                            ISBN = "978-954-01-0003-3",
                            PublishYear = 1997,
                            Title = "Хари Потър и философският камък"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            AvailableCopies = 4,
                            CategoryId = 2,
                            ISBN = "978-954-01-0004-4",
                            PublishYear = 1954,
                            Title = "Властелинът на пръстените"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            AvailableCopies = 6,
                            CategoryId = 4,
                            ISBN = "978-954-01-0005-5",
                            PublishYear = 1949,
                            Title = "1984"
                        });
                });

            modelBuilder.Entity("LibraryProject.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Класически и съвременни произведения на български автори",
                            FloorNumber = 1,
                            Name = "Българска литература"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Научна фантастика, фентъзи и алтернативни светове",
                            FloorNumber = 2,
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Световна класика и признати шедьоври",
                            FloorNumber = 3,
                            Name = "Класическа литература"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Книги за общества в упадък и тоталитарни режими",
                            FloorNumber = 2,
                            Name = "Дистопия"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Вълнуващи приключенски романи и истории",
                            FloorNumber = 1,
                            Name = "Приключения"
                        });
                });

            modelBuilder.Entity("LibraryProject.Data.Models.Book", b =>
                {
                    b.HasOne("LibraryProject.Data.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryProject.Data.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryProject.Data.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryProject.Data.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
